<!--
This component pull the latestVersion of Airnode from the config.js file
and creates a redirect for each page using /airnode/latest/.
-->

<template>
  <div>
    <p>
      All redirects that begin with <code>/airnode/latest/</code> have been auto
      generated by the list below. Currently the latest version of Airnode
      (<code>latestVersion</code>) in the <code>/config.js</code> file is
      <span v-if="latestAirnodeVersion"
        ><code>{{ latestAirnodeVersion }}</code></span
      >.
    </p>

    <p>
      When the <code>latestVersion</code> changes the display below will
      self-update. The following redirects should be copied and pasted into
      <code>/docs/.vuepress/redirects`</code> if they differ from the list
      below. Be sure to remove older redirects in the
      <code>/redirects</code> file that start with
      <code>/airnode/latest/</code>. It will be necessary to update the
      <code>/redirects</code> file when a new page is added to the docs.
    </p>

    <div id="v-for-object" class="demo">
      <code>
        <div v-for="value in this.routes" v-bind:key="value">
          {{ value }}
        </div>
      </code>
    </div>
  </div>
</template>

<script>
import { latestVersion } from '../config.js';
export default {
  name: 'LatestRedirects',
  data: () => ({
    routes: [],
    latestAirnodeVersion: null,
  }),
  mounted() {
    this.$nextTick(function () {
      this.latestAirnodeVersion = latestVersion;
      // Code that will run only after the entire view has been rendered.
      this.$site.pages.forEach((element) => {
        if (element.path.indexOf(latestVersion) > -1) {
          const latestRoute = element.path.replace(
            latestVersion,
            '/airnode/latest/'
          );
          this.routes.push(latestRoute + ' ' + element.path);
        }
      });
    });
  },
};
</script>

<style scoped>
hr {
  border-top: solid 2px gray;
}
</style>
