<!--
This component pulls the latest versions of versioned document sets
from the config.js file and creates a "latest" redirect for each page.
-->

<template>
  <div>
    <p>
      All redirects that begin with <code>/&#60;doc-set>>/latest/</code> have
      been auto generated by the list below.
    </p>

    <ul>
      <li>latestVersion:'/airnode/v0.4/'</li>
      <li>latestBeaconVersion: '/beacon/v0.1/'</li>
      <li>latestOisVersion: '/ois/v1.0.0/'</li>
    </ul>

    <p>
      When these versions change the display below will self-update. The
      following redirects should be copied and pasted into
      <code>/docs/.vuepress/redirects`</code> if they differ from the list
      below. It will be necessary to update the <code>/redirects</code> file
      when a new page is added to the docs.
    </p>

    <h3>Auto Generated List</h3>

    <div id="v-for-object" style="font-size: small">
      <div v-for="value in this.routes" v-bind:key="value">
        {{ value }}
      </div>
    </div>
  </div>
</template>

<script>
import {
  latestVersion,
  latestBeaconVersion,
  latestOisVersion,
} from '../config.js';
export default {
  name: 'LatestRedirects',
  data: () => ({
    routes: [],
  }),
  mounted() {
    this.$nextTick(function () {
      // Airnode
      this.$site.pages.forEach((element) => {
        if (element.path.indexOf(latestVersion) > -1) {
          const latestRoute = element.path.replace(
            latestVersion,
            '/airnode/latest/'
          );
          this.routes.push(latestRoute + ' ' + element.path);
        }
      });

      // Beacons
      this.$site.pages.forEach((element) => {
        if (element.path.indexOf(latestBeaconVersion) > -1) {
          const latestRoute = element.path.replace(
            latestBeaconVersion,
            '/beacon/latest/'
          );
          this.routes.push(latestRoute + ' ' + element.path);
        }
      });

      // OIS
      this.$site.pages.forEach((element) => {
        if (element.path.indexOf(latestOisVersion) > -1) {
          const latestRoute = element.path.replace(
            latestOisVersion,
            '/ois/latest/'
          );
          this.routes.push(latestRoute + ' ' + element.path);
        }
      });
    });
  },
};
</script>

<style scoped>
hr {
  border-top: solid 2px gray;
}
</style>
