name: Check links and images

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lychee_link_img_check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Cache lychee
        id: cache-lychee
        uses: actions/cache@v2
        with:
          path: ~/.cargo/bin/
          key: ${{ runner.os }}-lychee-

      - uses: actions-rs/toolchain@v1
        if: steps.cache-lychee.outputs.cache-hit != 'true'
        with:
          toolchain: stable

      - name: Run cargo install
        if: steps.cache-lychee.outputs.cache-hit != 'true'
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --git https://github.com/lycheeverse/lychee --rev dd9e24b7f454d9f08eb24c170cc757e134432210

      - name: Link Checker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          find docs/
          -not -path "*/.vuepress/*"
          -not -path "docs/airnode/v0.8/*"
          -not -path "docs/beacon/v0.2/*"
          -type f -name "*.md" | xargs lychee - -c .github/workflows/lychee.toml
